apiVersion: v1
kind: ServiceAccount
metadata:
  name: alert-manager
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: monitoring
  name: alert-manager-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alert-manager-rolebinding
  namespace: monitoring
subjects:
- kind: ServiceAccount
  name: alert-manager
  namespace: monitoring
roleRef:
  kind: Role
  name: alert-manager-role
  apiGroup: rbac.authorization.k8s.io 